language: php

php:
  - 5.6
  - 7

branches:
  only:
  - master

install:
  - nvm install 8
  - npm install

env:
  global:
  - GH_REF: github.com/suginoki45/fundam.git
  - secure: "R7kyNeMeB+fV6ETm7GB2CDb1gDvgrTnb8mudiD76GRRiU9uSvHUMoVdTKbhiY+x8vd4SdhlsGJxUg+nqT4SuQ8Ju4w4O5HkrKHgfsE+7al1wV/LOKLGq7NGDMAhIOzhkQwm+C9jF8aP4W27WqDZ4e2GkWIoaEDFZaUw9w7aIguH1gBU8ogGfFbziPuJHGbeFIUI1SMJ2dhqjCAFQK05566MV1GrJEboUZESFfR7gWnHJhtkkdnmaL3gCwYoApbXSTryzA6RJRDvqNxUQZMPI3XjBU4geQMfKwjzPn2ddvbPP4n0p0Fo22g51RdB/AgrXN6FON32j95B077isq0tvMOEEWyl8BJRY/QKMb0wlwiR5lZ0dhTZKY2c+6hbK+p+ECOk24Ac3bmi0UnSrTPZgBCRGWWjL1qJJGbwLQxL1i504WHtwOYJVCdS8LWnrmGGi8P0GivmJd/LrqwDsHrPNRSK2gHJDOSyFQBIgrVATG/Z+f4zaDjh2A1Re14gaTNJZ9zoR6ZNdibaWm0eqYrZWSaD0OVO9yvaIF+a8pCDbWZxLw+c3gTrUkgctu3CMwqBFWBmdx+Sb7FN19Ev+/HElw6hbkVc+iOOoc4HSunBerLLkIH65IxHZ186N9K+nVaUShk9ub55k3Xf1y/DJ0B1VZVh60TPuRPWEi9E2ZFCuGfo="
